version: '1'
services:
  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - my-network
  mysql:
    image: mysql:latest
    container_name: 'mysql-db'
    ports:
      - 3306:3306
    volumes:
      - ~/.docker-conf/mysql/data:/var/lib/mysql
      - ~/.docker-conf/mysql/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: newpassword
      MYSQL_DATABASE: companyemail
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ~/.docker-conf/mongodb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    networks:
      - my-network
networks:
  my-network:
